# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievances',
            name='date_info',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
