# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170401_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievances',
            name='subject',
            field=models.CharField(default='Grievance', max_length=255),
        ),
    ]
