# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_grievances_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('image_field', models.ImageField(upload_to=b'')),
                ('details', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Grievances',
            new_name='Grievance',
        ),
    ]
