# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20170411_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grievance',
            old_name='grievance_type',
            new_name='grievance_permission',
        ),
    ]
