# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20170411_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='grievance_type',
            field=models.CharField(default='public', max_length=255),
        ),
    ]
