# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_grievance_grievance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='news_type',
            field=models.CharField(default='event', max_length=255),
        ),
    ]
