# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_whiteboarduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whiteboarduser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='whiteboarduser',
            name='token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='whiteboarduser',
            name='type',
            field=models.CharField(default='Student', max_length=50),
        ),
        migrations.AlterField(
            model_name='whiteboarduser',
            name='uid',
            field=models.TextField(blank=True),
        ),
    ]
