# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20170415_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
