# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20170415_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
