# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_assignments_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='info',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
