# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
