# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_auto_20170416_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='test',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
