# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_auto_20170416_1327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='StudentTest',
        ),
    ]
