# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_auto_20170416_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placement',
            old_name='details',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='placement',
            old_name='course',
            new_name='stream',
        ),
    ]
